# Generated by Django 3.2.6 on 2024-01-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='computadora',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('caracteristicas', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='telefono',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('caracteristicas', models.JSONField()),
            ],
        ),
    ]
